### ISSUE TITLE
Compute simple user statistics during course passing

### ISSUE THREAD

**Issue by IgorNikiforov** [mandarinSh/OpenPolyEdu#11]
There is an existing script that calculate user names and ids.

Based on that script logic we can count simple user statistic on course and implement a new py script.

The result file should contain:
 - user_id, 
 - user_name, 
 - total_events_generated, 
 - total_sessions, 
 - total_pages_visited, 
 - total_amount_of_comments_in_forum, 
 - etc.

Please, feel free to add more information into the result table if there is an idea. 

Based on the result table we will see the numbers and will try to made a corrections.

**Comment by mandarinSh** [comment]
This issue is resolving by [PR#16](https://github.com/mandarinSh/OpenPolyEdu/pull/16)

**Comment by mandarinSh** [comment]
[PR#16](https://github.com/mandarinSh/OpenPolyEdu/pull/16) is merged.
